name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Install Maven
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Set up Maven
      run: echo "MAVEN_HOME=/Users/mac/Documents/2_Learn/1_QA/Installations/apache-maven-3.9.8" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn -B clean test -Ptestng
